name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install dependencies with pip + requirements.txt
        run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt
          .venv/bin/pip install -r requirements_develop.txt
          .venv/bin/pip install -e submodules/steamfiles

      - name: Move the dependencies
        run: mv .venv /home/runner/work/_temp/_github_workflow

      - name: Get Python version from .python-version file
        id: get-python-version
        run: echo "python-version=$(cut -d '.' -f 1,2 .python-version)" >> "$GITHUB_OUTPUT"

      - name: Super-linter
        uses: super-linter/super-linter/slim@v6.7.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          PYTHONPATH: "/github/workspace/:\
            /github/workflow/.venv/lib/python3.11/site-packages"
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_CHECKOV: true
          VALIDATE_JSCPD: true
          VALIDATE_MARKDOWN: true
          VALIDATE_VALIDATE_NATURAL_LANGUAGE: true
          # Linter not up to date
          GITHUB_ACTIONS_COMMAND_ARGS: >-
            -ignore 'unknown permission scope "attestations"'
            -ignore '"ubuntu-24.04" is unknown'
          PYTHON_RUFF_CONFIG_FILE: pyproject.toml
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml
          FILTER_REGEX_EXCLUDE: "LICENSE.md"
