name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request: null
  merge_group:

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          activate-environment: true

      - name: Install Dependencies
        shell: bash
        run: uv sync --locked --dev

      - name: Move the dependencies # Needed to deal with weirdness with super-linter's internal MyPy.
        run: mv .venv /home/runner/work/_temp/_github_workflow

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.2.1 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          PYTHONPATH: "/github/workspace/:\
            /github/workflow/.venv/lib/python3.12/site-packages"
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_CHECKOV: true
          VALIDATE_JSCPD: true
          VALIDATE_VALIDATE_NATURAL_LANGUAGE: true
          # Linter not up to date
          GITHUB_ACTIONS_COMMAND_ARGS: >-
            -ignore 'unknown permission scope "attestations"'
          PYTHON_RUFF_CONFIG_FILE: pyproject.toml
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml
          FILTER_REGEX_EXCLUDE: "LICENSE.md|super-linter-output/|github_conf/"
          IGNORE_GITIGNORED_FILES: true
          # Set your fix mode variables to true
          FIX_PYTHON_RUFF: true
      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests from the same repository
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          add_options: "-- . :!super-linter-output/ :!github_conf/"
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
